### PR TITLE
FMN standardizing

### PR DESCRIPTION
**Pull request by james02135**

### CODE REVIEW

**Comment by james02135** [comment]
@Zlopez Can you review when you get a free minute?

**Comment by Zlopez** [comment]
Shouldn't we add the artifact as well if known?

**Comment by james02135** [comment]
Which artifact is missing?

**Comment by Zlopez** [comment]
If I'm not mistaken, the FMN supports `artifact` parameter in message. Hotness knows about that when it fills a new update, because it already checked that this is a package in Fedora. This is however not true for all topics.

**Comment by Zlopez** [comment]
@james02135 Do you want to look at the `artifact` or should I just merge it how it is?

**Comment by james02135** [comment]
@Zlopez I'd say just to merge it and I can always put another PR in later if need be

**Pull request merged**
